const mockData = {
  data: [
    {
      name: 'Mixmax',
      budget_name: 'Software subscription',
      owner_id: 1,
      spent: {
        value: 100,
        currency: 'SGD',
      },
      available_to_spend: {
        value: 1000,
        currency: 'SGD',
      },
      card_type: 'burner',
      expiry: '9 Feb',
      limit: 100,
      status: 'active',
    },
    {
      name: 'Quickbooks',
      budget_name: 'Software subscription',
      owner_id: 2,
      spent: {
        value: 50,
        currency: 'SGD',
      },
      available_to_spend: {
        value: 250,
        currency: 'SGD',
      },
      card_type: 'subscription',
      limit: 10,
      status: 'active',
    },
    {
      name: 'Card 3',
      budget_name: 'Budget 3',
      owner_id: 3,
      spent: {
        value: 200,
        currency: 'USD',
      },
      available_to_spend: {
        value: 800,
        currency: 'USD',
      },
      card_type: 'burner',
      expiry: '31 Dec',
      limit: 500,
      status: 'active',
    },
    {
      name: 'Card 4',
      budget_name: 'Budget 4',
      owner_id: 4,
      spent: {
        value: 75,
        currency: 'EUR',
      },
      available_to_spend: {
        value: 2500,
        currency: 'EUR',
      },
      card_type: 'burner',
      expiry: '30 Nov',
      limit: 2000,
      status: 'active',
    },
    {
      name: 'Card 5',
      budget_name: 'Budget 5',
      owner_id: 5,
      spent: {
        value: 120,
        currency: 'GBP',
      },
      available_to_spend: {
        value: 880,
        currency: 'GBP',
      },
      card_type: 'burner',
      expiry: '15 Jan',
      limit: 300,
      status: 'active',
    },
    {
      name: 'Card 6',
      budget_name: 'Budget 6',
      owner_id: 6,
      spent: {
        value: 90,
        currency: 'USD',
      },
      available_to_spend: {
        value: 1000,
        currency: 'USD',
      },
      card_type: 'subscription',
      expiry: '30 Sep',
      limit: 800,
      status: 'active',
    },
    {
      name: 'Card 7',
      budget_name: 'Budget 7',
      owner_id: 7,
      spent: {
        value: 150,
        currency: 'EUR',
      },
      available_to_spend: {
        value: 3000,
        currency: 'EUR',
      },
      card_type: 'subscription',
      expiry: '31 Oct',
      limit: 2500,
      status: 'active',
    },
    {
      name: 'Card 8',
      budget_name: 'Budget 8',
      owner_id: 8,
      spent: {
        value: 80,
        currency: 'GBP',
      },
      available_to_spend: {
        value: 600,
        currency: 'GBP',
      },
      card_type: 'burner',
      expiry: '15 Dec',
      limit: 400,
      status: 'active',
    },
    {
      name: 'Card 9',
      budget_name: 'Budget 9',
      owner_id: 9,
      spent: {
        value: 180,
        currency: 'USD',
      },
      available_to_spend: {
        value: 1200,
        currency: 'USD',
      },
      card_type: 'subscription',
      expiry: '31 Jan',
      limit: 1000,
      status: 'active',
    },
    {
      name: 'Card 10',
      budget_name: 'Budget 10',
      owner_id: 10,
      spent: {
        value: 70,
        currency: 'EUR',
      },
      available_to_spend: {
        value: 2000,
        currency: 'EUR',
      },
      card_type: 'subscription',
      expiry: '28 Feb',
      limit: 1500,
      status: 'active',
    },
    {
      name: 'Card 11',
      budget_name: 'Budget 11',
      owner_id: 11,
      spent: {
        value: 100,
        currency: 'GBP',
      },
      available_to_spend: {
        value: 400,
        currency: 'GBP',
      },
      card_type: 'subscription',
      expiry: '31 Mar',
      limit: 200,
      status: 'active',
    },
  ],
  page: 1,
  per_page: 10,
  total: 100,
};

export default mockData;
